import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "My chat",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <script
          src="https://cdn.scaledrone.com/scaledrone.min.js"
          type="text/javascript"
        ></script>
        <script src="http://localhost:8097"></script>
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
